[CmdletBinding()]
param(
	[Parameter(Mandatory = $false)]
	[string]$Workload,

	[Parameter(Mandatory = $false)]
	[ValidateSet('Cloud', 'Host')]
	[string]$CollectionMode,

	[Parameter(Mandatory = $false)]
	[switch]$ListWorkloads,

	[Parameter(Mandatory = $false)]
	[switch]$NonInteractive,

	[Parameter(Mandatory = $false)]
	[hashtable]$Parameters = @{}
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$workloadModulePath = Join-Path -Path $PSScriptRoot -ChildPath 'scripts\common\Discovery.Workloads.psm1'
$definitionDirectory = Join-Path -Path $PSScriptRoot -ChildPath 'scripts\workloads'
if (-not (Test-Path -Path $workloadModulePath)) {
	throw "Workload registry module not found: $workloadModulePath"
}

Import-Module -Name $workloadModulePath -Force -ErrorAction Stop
Import-DiscoveryWorkloadDefinitions -DefinitionDirectory $definitionDirectory
$isGuidedSession = [string]::IsNullOrWhiteSpace($Workload)

$definitionErrors = @(Test-DiscoveryWorkloads)
if ($definitionErrors.Count -gt 0) {
	throw "Invalid workload definition(s): $($definitionErrors -join '; ')"
}

if ($ListWorkloads.IsPresent) {
	Get-DiscoveryWorkloads | Select-Object Name, DisplayName, CollectionMode, Capabilities, RequiredModules
	return
}

function Read-DiscoveryChoice {
	param([string]$Prompt, [string[]]$Choices, [string]$DefaultChoice)

	while ($true) {
		$value = (Read-Host $Prompt).Trim()
		if ([string]::IsNullOrWhiteSpace($value) -and -not [string]::IsNullOrWhiteSpace($DefaultChoice)) { return $DefaultChoice }
		$match = @($Choices | Where-Object { $_ -ieq $value } | Select-Object -First 1)
		if ($match.Count -eq 1) { return $match[0] }
		Write-Host "Enter one of: $($Choices -join ', ')." -ForegroundColor Yellow
	}
}

function Read-DiscoveryRequiredValue {
	param([string]$Prompt)

	while ($true) {
		$value = (Read-Host $Prompt).Trim()
		if (-not [string]::IsNullOrWhiteSpace($value)) { return $value }
		Write-Host 'A value is required.' -ForegroundColor Yellow
	}
}

if ($isGuidedSession) {
	if ($NonInteractive) { throw 'Specify -Workload or use -ListWorkloads to view available workloads.' }

	$availableWorkloads = @(Get-DiscoveryWorkloads | Sort-Object -Property DisplayName)
	Write-Host ''
	Write-Host 'Discovery collection' -ForegroundColor Cyan
	Write-Host 'Select the service you want to assess.'
	for ($index = 0; $index -lt $availableWorkloads.Count; $index++) {
		Write-Host ("  {0}. {1}" -f ($index + 1), $availableWorkloads[$index].DisplayName)
	}
	Write-Host '  Q. Exit'

	while ($true) {
		$selection = (Read-Host 'Selection').Trim()
		if ($selection -ieq 'q') { return }
		$selectionNumber = 0
		if ([int]::TryParse($selection, [ref]$selectionNumber) -and $selectionNumber -ge 1 -and $selectionNumber -le $availableWorkloads.Count) {
			$Workload = $availableWorkloads[$selectionNumber - 1].Name
			break
		}
		Write-Host "Enter a number from 1 to $($availableWorkloads.Count), or Q to exit." -ForegroundColor Yellow
	}
}

$selectedWorkload = Get-DiscoveryWorkload -Name $Workload
if ($null -eq $selectedWorkload) {
	$available = @(Get-DiscoveryWorkloads | ForEach-Object { $_.Name }) -join ', '
	throw "Unknown workload '$Workload'. Available workloads: $available"
}

if ([string]::IsNullOrWhiteSpace($CollectionMode)) {
	if ($selectedWorkload.CollectionMode -eq 'Both') {
		if (-not $isGuidedSession -or $NonInteractive) { throw "Workload '$Workload' supports both Cloud and Host collection. Specify -CollectionMode." }
		Write-Host ''
		Write-Host "$($selectedWorkload.DisplayName) supports two collection types:"
		Write-Host '  Cloud - Azure configuration, capacity, and usage metrics.'
		Write-Host '  Host  - Configuration of this Windows machine.'
		$CollectionMode = Read-DiscoveryChoice -Prompt 'Collection type [Cloud/Host]' -Choices @('Cloud', 'Host')
	}
	else {
		$CollectionMode = $selectedWorkload.CollectionMode
	}
}

if ($selectedWorkload.CollectionMode -ne 'Both' -and $selectedWorkload.CollectionMode -ne $CollectionMode) {
	throw "Workload '$Workload' does not support $CollectionMode collection."
}

$entryScript = if ($CollectionMode -eq 'Cloud') {
	$selectedWorkload.CloudEntryScript
}
else {
	$selectedWorkload.HostEntryScript
}

if ([string]::IsNullOrWhiteSpace($entryScript) -or -not (Test-Path -Path $entryScript -PathType Leaf)) {
	throw "Workload '$Workload' does not have a valid $CollectionMode entry script."
}

if ($Parameters.Count -eq 0 -and -not $NonInteractive -and $isGuidedSession) {
	Write-Host ''
	Write-Host 'Collection details' -ForegroundColor Cyan
	$Parameters.CustomerAbbreviation = Read-DiscoveryRequiredValue -Prompt 'Customer abbreviation'
	$generatedBy = (Read-Host 'Generated by (optional)').Trim()
	if ($generatedBy) { $Parameters.GeneratedBy = $generatedBy }
	$projectCode = (Read-Host 'Project code (optional)').Trim()
	if ($projectCode) { $Parameters.ProjectCode = $projectCode }
	if ((Read-DiscoveryChoice -Prompt 'Generate an HTML report? [Y/n]' -Choices @('Y', 'N') -DefaultChoice 'Y') -eq 'N') { $Parameters.NoHtml = $true }

	if ($Workload -eq 'Avd' -and $CollectionMode -eq 'Cloud') {
		if ((Read-DiscoveryChoice -Prompt 'Use the current Azure terminal context? [Y/n]' -Choices @('Y', 'N') -DefaultChoice 'Y') -eq 'Y') { $Parameters.UseCurrentContext = $true }
		$lookbackDays = Read-DiscoveryChoice -Prompt 'Metrics lookback days [30]' -Choices @(1..90 | ForEach-Object { $_.ToString() }) -DefaultChoice '30'
		$Parameters.LookbackDays = [int]$lookbackDays
		if ((Read-DiscoveryChoice -Prompt 'Exclude weekend data? [y/N]' -Choices @('Y', 'N') -DefaultChoice 'N') -eq 'Y') { $Parameters.ExcludeWeekends = $true }
		if ((Read-DiscoveryChoice -Prompt 'Limit metrics to local peak hours? [y/N]' -Choices @('Y', 'N') -DefaultChoice 'N') -eq 'Y') { $Parameters.PeakHoursOnly = $true }
		if ((Read-DiscoveryChoice -Prompt 'Run remote session-host discovery? [y/N]' -Choices @('Y', 'N') -DefaultChoice 'N') -eq 'Y') { $Parameters.RunLocalDiscovery = $true }
	}
	if ($Workload -eq 'RDS' -and $CollectionMode -eq 'Host') {
		$connectionBroker = (Read-Host 'Connection Broker FQDN (optional)').Trim()
		if ($connectionBroker) { $Parameters.ConnectionBroker = $connectionBroker }
	}

	Write-Host ''
	Write-Host ("Ready to run {0} ({1})." -f $selectedWorkload.DisplayName, $CollectionMode) -ForegroundColor Cyan
	if ((Read-DiscoveryChoice -Prompt 'Start collection? [Y/n]' -Choices @('Y', 'N') -DefaultChoice 'Y') -eq 'N') { return }
}

& $entryScript @Parameters